"""empty message

Revision ID: cd492ae3b1ce
Revises: 1d3008fdbdcb
Create Date: 2018-12-15 16:22:17.548372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd492ae3b1ce'
down_revision = '1d3008fdbdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.String(length=300), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'about')
    # ### end Alembic commands ###
